"""schema inicial (igual ao commit 1be9a89)

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 01:25:39.720305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque',
    sa.Column('cod_estoque', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('cod_dono', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('cod_estoque')
    )
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estoque_cod_estoque'), ['cod_estoque'], unique=False)

    op.create_table('item',
    sa.Column('cod_item', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('categoria', sa.String(length=300), nullable=False),
    sa.Column('cod_estoque', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cod_estoque'], ['estoque.cod_estoque'], ),
    sa.PrimaryKeyConstraint('cod_item')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_cod_estoque'), ['cod_estoque'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_cod_item'), ['cod_item'], unique=False)

    op.create_table('listacompra',
    sa.Column('cod_lista', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('cod_estoque', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['cod_estoque'], ['estoque.cod_estoque'], ),
    sa.PrimaryKeyConstraint('cod_lista')
    )
    with op.batch_alter_table('listacompra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listacompra_cod_lista'), ['cod_lista'], unique=False)

    op.create_table('usuario',
    sa.Column('cod_usuario', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=500), nullable=False),
    sa.Column('permissao', sa.String(length=500), nullable=False),
    sa.Column('cod_estoque', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cod_estoque'], ['estoque.cod_estoque'], ),
    sa.PrimaryKeyConstraint('cod_usuario')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_cod_usuario'), ['cod_usuario'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('convite_estoque',
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('cod_estoque', sa.BigInteger(), nullable=False),
    sa.Column('criado_por', sa.BigInteger(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_por', sa.BigInteger(), nullable=True),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cod_estoque'], ['estoque.cod_estoque'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.cod_usuario'], ),
    sa.ForeignKeyConstraint(['usado_por'], ['usuario.cod_usuario'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('itemestoque',
    sa.Column('cod_item', sa.BigInteger(), nullable=False),
    sa.Column('cod_estoque', sa.BigInteger(), nullable=False),
    sa.Column('qtd_desejada', sa.Integer(), nullable=False),
    sa.Column('qtd_estoque', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_estoque'], ['estoque.cod_estoque'], ),
    sa.ForeignKeyConstraint(['cod_item'], ['item.cod_item'], ),
    sa.PrimaryKeyConstraint('cod_item', 'cod_estoque')
    )
    op.create_table('listaitem',
    sa.Column('cod_item', sa.BigInteger(), nullable=False),
    sa.Column('cod_lista', sa.BigInteger(), nullable=False),
    sa.Column('qtd_desejada', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['cod_item'], ['item.cod_item'], ),
    sa.ForeignKeyConstraint(['cod_lista'], ['listacompra.cod_lista'], ),
    sa.PrimaryKeyConstraint('cod_item', 'cod_lista')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listaitem')
    op.drop_table('itemestoque')
    op.drop_table('convite_estoque')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))
        batch_op.drop_index(batch_op.f('ix_usuario_cod_usuario'))

    op.drop_table('usuario')
    with op.batch_alter_table('listacompra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listacompra_cod_lista'))

    op.drop_table('listacompra')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_cod_item'))
        batch_op.drop_index(batch_op.f('ix_item_cod_estoque'))

    op.drop_table('item')
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estoque_cod_estoque'))

    op.drop_table('estoque')
    # ### end Alembic commands ###
